export const ICONS = {
  VALIDATE: 'fa-regular fa-folder',
  SIGNATURE: 'fa-solid fa-file-signature',
  FOLDER: 'fa-solid fa-folder-closed',
  FILTER: 'fa-solid fa-filter',
  UPLOAD: 'fa-solid fa-cloud-arrow-up',
  MENU: 'fa-solid fa-bars-staggered',
  SETTING: 'fa-solid fa-gear',
  LOGOUT: 'fa-solid fa-arrow-right-from-bracket',
  LEFT: 'fa-solid fa-square-caret-left',
  RIGHT: 'fa-solid fa-square-caret-right',
  GOOGLE: 'fa-brands fa-google',
  CLOSE: 'fa-solid fa-xmark',
  SHIELD: 'fa-solid fa-shield-halved',
};
